### ISSUE TITLE
Supported payment types

### ISSUE THREAD

**Issue by georgstrieder** [fiskaly/fiskaly-sdk-swift#12]
Which payment types are supported by the Fiskaly KassenSichV API? NON_CASH and CASH are used in the examples. But according to DSFinV more payment types are provided:
- Bar (= CASH)
- Unbar (= NON_CASH)
- None (= ???)
- EC card (= ???)
- Credit card (= ???)
- E-payment service provider (= ???)
- Credit card (= ???)

**Comment by prempador** [comment]
Hello @georgstrieder, thanks for the question.

The TSS only has to differentiate between CASH and NON_CASH. This is the reason why these are the only two types available.
There will be another schema in the future that will have the other types.

As this question has come up multiple times now we will add it to the API Documentation.
