### ISSUE TITLE
JSONRpc Error -> Order Update Transaction

### ISSUE THREAD

**Issue by ghost** [fiskaly/fiskaly-sdk-swift#25]
Hello, im trying to reproduce the Order Update Transaction but I get an Error:

FiskalySDK.JsonRpcError
2020-07-28 14:15:59.467193+0200 Runner[23874:5438544] Unsupported value: <invalid NS/CF object> of type FiskalySDK.JsonRpcError

Here is my Transaction Body:

`let transactionBody : [String: Any] = [
                   "state": "ACTIVE",
                   "client_id": self.client_id,
                   "schema": [
                       "standard_v1": [
                           "order": [
                            "line_items": [
                                [
                                "quantity": "1",
                                "text": "Beer",
                                "price_per_unit": "6.00"
                                ]
                            ]
                           ]
                       ]
                     ]
            ]`

**Comment by gastrolize** [comment]
I tried it now with postmen and I get the message: "429 Too Many Requests"

I think my mistake was to creating to many clients instances per transaction function, that's maybe why I get this JsonRPC Error or am I wrong?

But if its because of that, does the SDK automatically reget the bearer if its expired ?

**Comment by ghost** [comment]
Fixed, it was because of the price_per_unit: I sent before 10.0 not 10.00 and after that I got 429 so that's why the sample from the FiskalySDKDemo not worked
