### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by marcelvoss** [fiskaly/fiskaly-sdk-swift#8]
Hi there,

as I'm currently submitting multiple issues to this repository (and some of them being rather easy to fix), I wondered about the contribution guidelines for this project. Is it safe to contribute? What are requirements for contributing?

Thanks

**Comment by prempador** [comment]
Hello @marcelvoss,

thank you for taking the time and addressing various issues with the fiskaly Swift SDK. 

I am currently working on updating the issue and pull-request templates for all the new SDK iterations we pushed in the last view days. I will also look into adding contribution guidelines. 

The current state of the SDK is a first implementation that will need some work, as you pointed out, to be easy and safe to use. We wanted to provide a base SDK that uses our [fiskaly client](https://developer.fiskaly.com/en/docs/client-documentation), to enable developers who wanted to start the integration of our services. As this is an early implementation, there is the possibility of changes in the SDK. 

With this in mind we are looking forward to any contributions from people outside of our company, as this is one of the reasons we made the SDK open source. Therefore contributing is allowed, as long as it is a reasonable change and tests are provided to ensure the functionality. I will write all of this down in the contribution guidelines. For now, you can already start with addressing issues if you want to (please make sure to let anyone know what issue you are working on, so we don't work on the same issue). 
We are also taking any feedback and requests into consideration that may improve our SDK. 

We have some plans for the next few weeks to implement more things (not in this particular order): 

- Templates and Guidelines as mentioned above
- CI / CD (e.g. Github Actions, Sonarcloud)
- Adding a Changelog for the SDK
- Automatic JSON Serialization and Parsing of our API Endpoints
- Adding more documentation and clearer instructions
- Adding Dependency Managers (e.g. Cocoapods)
- Creating a Demo-App in the App Store that uses our SDK

I hope I was able to answer some of your questions, at least for now. I will keep updating this issue as I have more information or any updates regarding this topic. 

Thank you again for taking your time to help us improve our SDK
